### PR TITLE
Adds postgres >=9.2.16 support and more flexible configuration options

### PR DESCRIPTION
**Pull request by kevin-cantwell**
This PR does two things:
1) Alters the setup sql scripts so as to be postgres 9.2 compatible. Tests are now executed against a 9.2.16 docker image. Specifically, the `CREATE SCHEMA IF NOT EXISTS` syntax was problematic as well as the use of the `json_agg` function. Both of which were introduced in 9.3.
2) Alters the way databases are configured, adding an `options` section under `database` in the yaml configs. Options are key/value and are included in the postgres connection string. In this way one may add arbitrary options such as `sslmode=require`. Example:

```yaml
database:
  name: "test-db"
  database: "postgres"
  hostname: "postgres"
  username: "postgres"
  password: "root"
  port: 5432
  options:
    sslmode: disable
```

### CODE REVIEW

**Comment by kevin-cantwell** [comment]
Addresses https://github.com/pagarme/teleport/issues/10

**Comment by pedrofranceschi** [comment]
Hi Kevin,

Thanks for the PR! Could you please remove the _workspace from Godeps?

**Comment by pedrofranceschi** [comment]
@kevin-cantwell did you have a chance to check my comments? I'm looking forward to merge this!

**Comment by kevin-cantwell** [comment]
Sure thing. Question before I do: Do you normally leave out the _workspace from your projects? How are you enforcing dependencies?

In our projects we always commit the _workspace because if we don't we've found they're not always reproduceable from the Godeps.json file alone. Ie: Packages can disappear from repos (we've seen it happen on several occasions).

**Comment by greenboxal** [comment]
@kevin-cantwell We're using Go 1.5 vendor experiment which is not an experiment anymore in 1.6. It's in the `vendor` directory.

**Comment by kevin-cantwell** [comment]
Oh how did I miss it! Ha, great!

**Comment by pedrofranceschi** [comment]
Thanks! :-)

**Pull request merged**
